[package]
name = "capngraph"
version = "0.2.0"
authors = ["J David Smith <emallson@atlanis.net>"]
build = "build.rs"
license = "BSD-3-Clause"

[dependencies]
capnp = "0.7"
petgraph = "0.4.1"
docopt = "*"
rustc-serialize = "0.3"
bit-set = "0.4"

[build-dependencies]
capnpc = "0.7"
